package pojos;
// Generated 04-jul-2017 14:07:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Activitat generated by hbm2java
 */
public class Activitat  implements java.io.Serializable {


     private Integer idActivitat;
     private String codi;
     private String descripcio;
     private Set registres = new HashSet(0);

    public Activitat() {
    }

	
    public Activitat(String codi) {
        this.codi = codi;
    }
    public Activitat(String codi, String descripcio, Set registres) {
       this.codi = codi;
       this.descripcio = descripcio;
       this.registres = registres;
    }
   
    public Integer getIdActivitat() {
        return this.idActivitat;
    }
    
    public void setIdActivitat(Integer idActivitat) {
        this.idActivitat = idActivitat;
    }
    public String getCodi() {
        return this.codi;
    }
    
    public void setCodi(String codi) {
        this.codi = codi;
    }
    public String getDescripcio() {
        return this.descripcio;
    }
    
    public void setDescripcio(String descripcio) {
        this.descripcio = descripcio;
    }
    public Set getRegistres() {
        return this.registres;
    }
    
    public void setRegistres(Set registres) {
        this.registres = registres;
    }




}


