package pojos;
// Generated 04-jul-2017 14:07:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Centre generated by hbm2java
 */
public class Centre  implements java.io.Serializable {


     private Integer idCentre;
     private String nom;
     private String codi;
     private String telefon;
     private String web;
     private Set usuaris = new HashSet(0);
     private Set alumnes = new HashSet(0);

    public Centre() {
    }

	
    public Centre(String nom, String codi, String telefon, String web) {
        this.nom = nom;
        this.codi = codi;
        this.telefon = telefon;
        this.web = web;
    }
    public Centre(String nom, String codi, String telefon, String web, Set usuaris, Set alumnes) {
       this.nom = nom;
       this.codi = codi;
       this.telefon = telefon;
       this.web = web;
       this.usuaris = usuaris;
       this.alumnes = alumnes;
    }
   
    public Integer getIdCentre() {
        return this.idCentre;
    }
    
    public void setIdCentre(Integer idCentre) {
        this.idCentre = idCentre;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCodi() {
        return this.codi;
    }
    
    public void setCodi(String codi) {
        this.codi = codi;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public Set getUsuaris() {
        return this.usuaris;
    }
    
    public void setUsuaris(Set usuaris) {
        this.usuaris = usuaris;
    }
    public Set getAlumnes() {
        return this.alumnes;
    }
    
    public void setAlumnes(Set alumnes) {
        this.alumnes = alumnes;
    }




}


