package pojos;
// Generated 04-jul-2017 14:07:34 by Hibernate Tools 4.3.1



/**
 * Registre generated by hbm2java
 */
public class Registre  implements java.io.Serializable {


     private RegistreId id;
     private Activitat activitat;
     private Alumne alumne;
     private int hores;

    public Registre() {
    }

    public Registre(RegistreId id, Activitat activitat, Alumne alumne, int hores) {
       this.id = id;
       this.activitat = activitat;
       this.alumne = alumne;
       this.hores = hores;
    }
   
    public RegistreId getId() {
        return this.id;
    }
    
    public void setId(RegistreId id) {
        this.id = id;
    }
    public Activitat getActivitat() {
        return this.activitat;
    }
    
    public void setActivitat(Activitat activitat) {
        this.activitat = activitat;
    }
    public Alumne getAlumne() {
        return this.alumne;
    }
    
    public void setAlumne(Alumne alumne) {
        this.alumne = alumne;
    }
    public int getHores() {
        return this.hores;
    }
    
    public void setHores(int hores) {
        this.hores = hores;
    }




}


