package pojos;
// Generated 04-jul-2017 14:07:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegistreId generated by hbm2java
 */
public class RegistreId  implements java.io.Serializable {


     private int idActivitat;
     private int idAlumne;
     private Date data;

    public RegistreId() {
    }

    public RegistreId(int idActivitat, int idAlumne, Date data) {
       this.idActivitat = idActivitat;
       this.idAlumne = idAlumne;
       this.data = data;
    }
   
    public int getIdActivitat() {
        return this.idActivitat;
    }
    
    public void setIdActivitat(int idActivitat) {
        this.idActivitat = idActivitat;
    }
    public int getIdAlumne() {
        return this.idAlumne;
    }
    
    public void setIdAlumne(int idAlumne) {
        this.idAlumne = idAlumne;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistreId) ) return false;
		 RegistreId castOther = ( RegistreId ) other; 
         
		 return (this.getIdActivitat()==castOther.getIdActivitat())
 && (this.getIdAlumne()==castOther.getIdAlumne())
 && ( (this.getData()==castOther.getData()) || ( this.getData()!=null && castOther.getData()!=null && this.getData().equals(castOther.getData()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdActivitat();
         result = 37 * result + this.getIdAlumne();
         result = 37 * result + ( getData() == null ? 0 : this.getData().hashCode() );
         return result;
   }   


}


