package pojos;
// Generated 04-jul-2017 14:07:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuari generated by hbm2java
 */
public class Usuari  implements java.io.Serializable {


     private Integer idUsuari;
     private Centre centre;
     private String nif;
     private String password;
     private String nom;
     private String primerCognom;
     private String segonCognom;
     private Date dataAlta;
     private String mail;
     private int permisos;
     private Alumne alumne;
     private Tutor tutor;

    public Usuari() {
    }

	
    public Usuari(String nif, String password, String nom, String primerCognom, String segonCognom, Date dataAlta, String mail, int permisos) {
        this.nif = nif;
        this.password = password;
        this.nom = nom;
        this.primerCognom = primerCognom;
        this.segonCognom = segonCognom;
        this.dataAlta = dataAlta;
        this.mail = mail;
        this.permisos = permisos;
    }
    public Usuari(Centre centre, String nif, String password, String nom, String primerCognom, String segonCognom, Date dataAlta, String mail, int permisos, Alumne alumne, Tutor tutor) {
       this.centre = centre;
       this.nif = nif;
       this.password = password;
       this.nom = nom;
       this.primerCognom = primerCognom;
       this.segonCognom = segonCognom;
       this.dataAlta = dataAlta;
       this.mail = mail;
       this.permisos = permisos;
       this.alumne = alumne;
       this.tutor = tutor;
    }
   
    public Integer getIdUsuari() {
        return this.idUsuari;
    }
    
    public void setIdUsuari(Integer idUsuari) {
        this.idUsuari = idUsuari;
    }
    public Centre getCentre() {
        return this.centre;
    }
    
    public void setCentre(Centre centre) {
        this.centre = centre;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrimerCognom() {
        return this.primerCognom;
    }
    
    public void setPrimerCognom(String primerCognom) {
        this.primerCognom = primerCognom;
    }
    public String getSegonCognom() {
        return this.segonCognom;
    }
    
    public void setSegonCognom(String segonCognom) {
        this.segonCognom = segonCognom;
    }
    public Date getDataAlta() {
        return this.dataAlta;
    }
    
    public void setDataAlta(Date dataAlta) {
        this.dataAlta = dataAlta;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public int getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(int permisos) {
        this.permisos = permisos;
    }
    public Alumne getAlumne() {
        return this.alumne;
    }
    
    public void setAlumne(Alumne alumne) {
        this.alumne = alumne;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }
}


